server:
  port: 80
spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes:
        - id: mall-auth-admin
          uri: http://localhost:8001
          predicates:
            - Path=/maa/**
        - id: mall-web-base-admin
          uri: http://localhost:9001
          predicates:
            - Path=/mwb/admin/**
        - id: mall-web-system-admin
          uri: http://localhost:9002
          predicates:
            - Path=/mws/admin/**

