server:
  port: 80
spring:
  application:
    name: mall-gateway
  cloud:
    gateway:
      routes:
        #后台admin端认证服务
        - id: mall-auth-admin
          uri: http://localhost:7001
          predicates:
            - Path=/admin/**
        #前台app端认证服务
        - id: mall-auth-app
          uri: http://localhost:8001
          predicates:
            - Path=/app/**
        #后台merchant端认证服务
        - id: mall-auth-merchant
          uri: http://localhost:9001
          predicates:
            - Path=/merchant/**

        - id: mall-web-base-admin
          uri: http://localhost:7002
          predicates:
            - Path=/admin/base/**
        - id: mall-web-system-admin
          uri: http://localhost:7003
          predicates:
            - Path=/admin/system/**
        - id: mall-web-member-app
          uri: http://localhost:8002
          predicates:
            - Path=/app/member/**

