server:
  port: 8002
spring:
  application:
    name: mall-web-app-base
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    database: mysql
    show-sql: true
    openInView: true
    properties:
      hibernate:
        format_sql: true
        dialect:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2ze09g9o0bb02q5r54o.mysql.rds.aliyuncs.com:3306/mall-base?serverTimezone=GMT%2B8
    username: jinbihu_shop
    password: Jinbihu_2023
  data:
    redis:
      host: 182.92.64.247
      password: jinbihu2023
      client-type: lettuce
      database: 1
  cloud:
    openfeign:
      client:
        config:
          mall-web-app-base:
            loggerLevel: FULL
            contract: feign.Contract.Default
            connectTimeout: 5
            readTimeout: 4
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: '系统管理服务【后台】'
      paths-to-match: '/**'
      packages-to-scan: com.lingyi.mall.biz.system.b.controller
